### PR TITLE
Update from upstream

### PR DESCRIPTION
**Pull request by jeffbean**
pulling in updates from upstream

### CODE REVIEW

**Comment by alxn** [comment]
> try to get the basic test to not flake

this is a separate fix?

**Comment by alxn** [comment]
also how come you've got merge conflicts?

**Comment by jeffbean** [comment]
> > try to get the basic test to not flake
> 
> this is a separate fix?

it can be. ill do that first i guess.

**Comment by jeffbean** [comment]
> also how come you've got merge conflicts?

I soft forked, but some of it was upstreamed. this is preparing to hard fork. we need to remove a lot of cruft.

**Comment by alxn** [comment]
can you do over or rebase?

**Comment by jeffbean** [comment]
> can you do over or rebase?

yeah i can clean this up now. "plan changes"

**Pull request closed without merging**
